#!/usr/bin/env bash
set -e

want='staging'

if [ -f '.dpl' ]
then
  source '.dpl'

  echo "Export to {$DEPLOYMENT}."
  echo ""

  if [[ ! $want ]]
  then
    echo "not set"
  else
    eval target=\$"${want}_mysql"
    echo $target
  fi

while getopts ":a:" opt; do
  case $opt in
    a)
      echo "-a was triggered, Parameter: $OPTARG" >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
fi


# COMMAND="$1"
# if [ -z "$COMMAND" ]; then
#   echo "usage: dpl completions COMMAND [arg1 arg2...]" >&2
#   exit 1
# fi

# COMMAND_PATH="$(command -v "dpl-$COMMAND")"
# if grep -i "^# provide dpl completions" "$COMMAND_PATH" >/dev/null; then
#   shift
#   exec "$COMMAND_PATH" --complete "$@"
# fi